name: GitHub Actions Demo
on: [push]
jobs:
  ScanImage:
    runs-on: e-bot7
    steps:
      # - name: Docker Image List
      #   uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1        

      - name: List Images
        run: |
          # aws ecr describe-repositories
          aws ecr list-images --repository-name ecr-scan-poc

      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
