name: GitHub Actions Demo
on: [push]
jobs:
  AuthenticatewithECR:
    runs-on: e-bot7
    steps:
      # - name: Docker Image List
      #   uses: actions/checkout@v3

      - name: Docker Image List
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo ${{ env.AWS_ACCESS_KEY }}
          echo ${{ env.AWS_SECRET_KEY }}
          who am i
          docker images

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
