name: GitHub Actions Demo
on: [push]
jobs:
  AuthenticatewithECR:
    runs-on: e-bot7
    steps:
      # - name: Docker Image List
      #   uses: actions/checkout@v3

      - name: Docker Image List
        run: |
          who am i
          docker images

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
