name: GitHub Actions Demo
on: [push]
jobs:
  ScanImage:
    runs-on: e-bot7
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  

      - name: List Images
        run: |
          # aws ecr describe-repositories
          aws ecr list-images --repository-name ecr-scan-poc

      - name: Pull the image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity | jq -r '.Account')
          echo "DOCKER_IMAGE_TO_SCAN=${ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/ecr-scan-poc:latest" >> $GITHUB_ENV
          echo "Github Variables are: ${GITHUB_ENV}"


          # docker pull $DOCKER_IMAGE_TO_SCAN
          docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master

        with:
          image-ref: '${{ env.DOCKER_IMAGE_TO_SCAN }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v1
      #   if: always() 
      #   with:
      #     sarif_file: 'trivy-results.sarif'          
          
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
