name: GitHub Actions Demo
# on: [push]
on:
  pull_request:
    types: [opened, reopened]

jobs:
  VulnerabilityScanner:
    runs-on: e-bot7
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: get cwd
        run: |
          pwd